services:
  - type: web
    name: law-office-backend
    env: python
    buildCommand: |
      # Install Poetry
      curl -sSL https://install.python-poetry.org | python3 -
      export PATH="/opt/render/.local/bin:$PATH"
      # Install dependencies with Poetry
      poetry config virtualenvs.create false
      poetry install --no-dev
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: PORT
        value: 8000 